path: D:\dev\WildFire-Detection\TrainANDTest #dataset root directory
train: images/train #path to train images
val: images/val # path to validation images

# classes
nc: 1 # number of classes
names: ['fire'] # class names